### PR TITLE
fix: ACNA-2509 - zipfile does not exist due to hard-coded path

### PR DESCRIPTION
**Pull request by shazron**
## Description

daily asset compute integration smoke tests were failing:
https://github.com/adobe/aio-e2e-tests/actions/runs/6031496162

the test that failed:
https://github.com/adobe/asset-compute-integration-tests/blob/995c349be023326248cdfb2f7f8c182cb8a392e3/test/index.test.js#L64

The failure is due to the hard-coded location of the action zip -- this relied on legacy behaviour where we symlinked the old location of the zips to their new locations which in sub-folders named after the action's package name.

The symlinks were removed because they caused issues in Windows for devs: 
1. PR https://github.com/adobe/aio-lib-runtime/pull/150
2. Issue https://github.com/adobe/aio-cli-plugin-app/issues/604

This patch is better since it relies on the the zip locations returned by the runtime lib itself, and the locations are virtually guaranteed to exist.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
Not sure why the tests are failing - those are not related to my changes. I ran `npm test` locally and they passed

**Comment by shazron** [comment]
@badvision updated with tests. Tested locally only one test is failing (unrelated):
```
1) test-worker command
       success
         runs successful tests with a mocked domain:
     AssertionError [ERR_ASSERTION]: unexpected exit code: 2, expected: undefined
      at assertExitCode (test/commands/testutil.js:129:12)
      at Context.<anonymous> (test/commands/test-worker.test.js:175:17)
      at Object.run (node_modules/fancy-test/lib/base.js:44:38)
      at Context.run (node_modules/fancy-test/lib/base.js:68:36)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Review by badvision — APPROVED** [review]
👍🏼 Thanks for going the extra mile on these tests! 😄

**Comment by pheenomenon** [comment]
CI was failing due to failed docker login. fixed the credentials. Rerunning GitHub workflow is not picking up the creds. Can we close this PR and re-do it ?

**Comment by shazron** [comment]
CI can't access credentials to run docker login, off a forked repo. Will create a branch off this repo instead.

**Pull request closed without merging**
